# === 기본 설정 상속 ===
defaults:
  - babi

# === 뇌 영역 구성 (완전 오버라이드) ===
brain_regions:
  IN:
    grid_size: [64, 64]
    decay_rate: 1.0
    distance_tau: 0.7
  ACC:
    grid_size: [64, 64]
    decay_rate: 1.0
    distance_tau: 0.7
  PASS:
    grid_size: [64, 64]
    decay_rate: 1.0
    distance_tau: 0.7
  OUT:
    grid_size: [64, 64]
    decay_rate: 1.0
    distance_tau: 0.7
