# configs/phase2_babi_task1.yaml
# bAbI 추론 태스크 전용 설정

# === 기본 설정 상속 ===
defaults:
  - babi

# === 학습 설정 오버라이드 ===
learning:
  epochs: 1

data:
  train_samples: 1
  val_samples: 1
  test_samples: 1

# === 평가 설정 ===
evaluation:
  save_examples: 20
