# === 기본 설정 상속 ===
defaults:
  - babi

axonal_connections:
  connections:
    - source: "IN"
      target: "PASS"
      patch_size: 2
      patch_weight_scale: .5
      inner_weight_scale: 1.0
    - source: "PASS"
      target: "OUT"
      patch_size: 2
      patch_weight_scale: .5
      inner_weight_scale: 1.0
