# === 기본 설정 상속 ===
defaults:
  - babi

# === IO 시스템 ===
io_system:
  input_interface:
    embedding_dim: 512
    window_size: 16
    encoder_layers: 1
    encoder_heads: 8
    encoder_dropout: 0.1
    dim_feedforward: 2048
    input_power: 0.05
    softmax_temperature: 0.1
    t5_model_name: "t5-small"

  output_interface:
    embedding_dim: 512
    window_size: 16
    decoder_layers: 1
    decoder_heads: 8
    dim_feedforward: 2048
    dropout: 0.1
    t5_model_name: "t5-small"
    transplant_cross_attention: true
