# configs/base_model.yaml
# SCS 기본 모델 설정 - 표준화된 구조

# === 시스템 역할 정의 ===
system_roles:
  input_node: "IN"
  output_node: "OUT"

# === 뇌 영역 구성 (단순한 IN→OUT 구조) ===
brain_regions:
  IN:
    grid_size: [16, 16]
    decay_rate: 0.95
    distance_tau: 1.5
  OUT:
    grid_size: [16, 16]
    decay_rate: 0.88
    distance_tau: 2.0

# === 스파이크 역학 ===
spike_dynamics:
  threshold: 0.0
  refractory_base: 3
  refractory_adaptive_factor: 10.0
  surrogate_beta: 10.0
  ema_alpha: 0.1

# === 연결성 설정 ===
connectivity:
  local:
    max_distance: 5

# === 축삭 연결 (IN→OUT 단일 연결) ===
axonal_connections:
  excitatory_ratio: 0.8
  connections:
    - source: "IN"
      target: "OUT"
      kernel_size: 3
      stride: 1
      padding: 1
      dilation: 1
      weight_scale: 0.8

# === IO 시스템 ===
io_system:
  input_interface:
    embedding_dim: 512
    max_seq_len: 128
    num_heads: 8
    use_positional_encoding: true
  output_interface:
    embedding_dim: 256
    max_output_len: 128
    num_heads: 4
    num_decoder_layers: 2
    dim_feedforward: 1024
    dropout: 0.1

# === 적응적 출력 타이밍 ===
adaptive_output_timing:
  min_processing_clk: 100
  max_processing_clk: 500
  convergence_threshold: 0.1
  confidence_threshold: 0.8
  stability_window: 10
  start_output_threshold: 0.5
  min_output_length: 10
  fixed_len: -1

# === 학습 설정 ===
learning:
  epochs: 15
  learning_rate: 1e-3
  weight_decay: 1e-4
  gradient_clip_norm: 1.0
  eval_every: 3
  save_every: 10
  early_stopping_patience: 20
  max_clk_training: 250
  optimizer: "adamw"

  # Scheduled Sampling
  use_scheduled_sampling: false
  ss_start_prob: 1.0
  ss_end_prob: 0.05
  ss_decay_epochs: 10

  # 손실 함수 파라미터
  spike_reg_weight: 0.0
  temporal_weight: 0.0
  length_penalty_weight: 0.0
  target_spike_rate: 0.1
  timing_weight: 0.1
  start_threshold: 0.5
  confidence_threshold: 0.7

data:
  train_samples: -1 # -1은 전체 데이터, 양수는 해당 개수만
  val_samples: -1 # -1은 전체 데이터
  test_samples: -1 # -1은 전체 데이터

# === 데이터 로딩 ===
data_loading:
  batch_size: 8
  num_workers: 0
  tokenizer:
    name: "bert-base-uncased"
    max_length: 128

# === 작업 설정 ===
task:
  dataset_name: "datatune/LogiQA2.0"
  task_type: "auto"

# === 평가 설정 ===
evaluation:
  save_examples: 10
