# configs/base_model.yaml
# SCS 기본 모델 설정

# 시스템 설정
system:
  device: "auto" # auto, cuda, cpu, mps
  precision: "float32"
  random_seed: 42

# 뇌 영역별 설정
brain_regions:
  PFC:
    total_neurons: 512
    decay_rate: 0.95 # 긴 지속성 (작업 기억)
    distance_tau: 1.5 # 빠른 감쇠
    neurons_per_layer: [128, 205, 128, 51] # L1(25%), L2/3(40%), L4(25%), L5/6(10%) 비율

  ACC:
    total_neurons: 256
    decay_rate: 0.88 # 빠른 반응 (갈등 감지)
    distance_tau: 2.0
    neurons_per_layer: [64, 102, 64, 26]

  IPL:
    total_neurons: 384
    decay_rate: 0.92 # 중간 지속성 (관계 연합)
    distance_tau: 2.5
    neurons_per_layer: [96, 154, 96, 38]

  MTL:
    total_neurons: 256
    decay_rate: 0.97 # 장기 기억
    distance_tau: 3.0 # 넓은 연결
    neurons_per_layer: [64, 102, 64, 26]

# 스파이크 동역학 설정
spike_dynamics:
  threshold: 0.0
  refractory_base: 3
  refractory_adaptive_factor: 10.0
  surrogate_beta: 10.0

# 연결성 설정
connectivity:
  # 지역적 연결 (Roll 연산)
  local:
    max_distance: 5
    connection_prob: 0.1

  # 축삭 연결 (모듈 간)
  axonal:
    connection_prob: 0.1
    excitatory_ratio: 0.8 # 80% 흥분성, 20% 억제성

    # Multi-scale Grid 연결
    multi_scale_grids:
      fine:
        modules: 8
        spacing: 2
        weight: 0.5
      medium:
        modules: 4
        spacing: 3
        weight: 0.3
      coarse:
        modules: 2
        spacing: 5
        weight: 0.2

# 입출력 시스템
io_system:
  vocab_size: 50000
  embedding_dim: 512
  num_slots: 512
  attention_heads: 8
  confidence_threshold: 0.7

# 적응적 타이밍
timing:
  min_processing_clk: 50 # 50ms
  max_processing_clk: 500 # 500ms
  convergence_threshold: 0.1
  confidence_threshold: 0.7

# 학습 메커니즘
learning:
  # K-hop 제한 역전파
  k_hop_limit: 2

  # 신경조절 신호
  neuromodulation:
    dopamine_sensitivity: 2.0
    acetylcholine_sensitivity: 3.0
    stdp_modulation_strength: 0.1

  # STDP (기본 비활성화)
  stdp:
    enabled: false
    tau_pos: 20.0 # ms
    tau_neg: 20.0 # ms
    learning_rate: 1e-6
