# === 기본 설정 상속 ===
defaults:
  - mrpc

learning:
  gradual_unfreezing:
    enabled: true
    initial_frozen_patterns: # 시작할 때 동결할 파라미터들
      - "input_interface.token_embedding"
      - "input_interface.transformer_encoder"
      - "input_interface.pattern_mapper"

      - "output_interface.token_embedding"
      - "output_interface.final_projection"
      - "output_interface.hidden_norm"
      - "output_interface.spatial_compressor"
    unfreeze_schedule: # 에포크별 해제 스케줄
      0:
        - "output_interface.transformer_decoder.layers.0.multihead_attn"
        - "output_interface.transformer_decoder.layers.1.multihead_attn"
    freeze_schedule:
      1000:
        - "output_interface.spatial_compressor"
        - "input_interface.pattern_mapper"
