# configs/phase2_babi_bert.yaml
# bAbI 추론 태스크 전용 설정

# === 기본 설정 상속 ===
defaults:
  - base_model

# === 실험 메타정보 ===
experiment:
  name: "Phase2_bAbI_Task1"
  description: "bAbI Task 1: Single Supporting Fact"
  phase: 2
  expected_runtime: "30-60분"

# === 시스템 역할 (base와 동일하므로 생략 가능) ===
system_roles:
  input_node: "IN"
  output_node: "OUT"
  acc_node: "ACC"

# === 뇌 영역 구성 (완전 오버라이드) ===
brain_regions:
  IN:
    grid_size: [64, 64]
    decay_rate: 0.9
    distance_tau: 1.0
  ACC:
    grid_size: [64, 64]
    decay_rate: 0.9
    distance_tau: 1.0
  ADJ:
    grid_size: [64, 64]
    decay_rate: 0.9
    distance_tau: 1.0
  OUT:
    grid_size: [64, 64]
    decay_rate: 0.9
    distance_tau: 1.0

# === 축삭 연결 (완전 오버라이드) ===
axonal_connections:
  connections:
    # 기본 정보 처리 경로
    - source: "IN"
      target: "ADJ"
      kernel_size: 3
      stride: 1
      padding: 1
      dilation: 1
      weight_scale: 0.9

    - source: "ADJ"
      target: "IN"
      kernel_size: 5
      stride: 1
      padding: 2
      dilation: 1
      weight_scale: 0.2

    - source: "ADJ"
      target: "OUT"
      kernel_size: 3
      stride: 1
      padding: 1
      dilation: 1
      weight_scale: 0.9

    - source: "OUT"
      target: "ADJ"
      kernel_size: 5
      stride: 1
      padding: 2
      dilation: 1
      weight_scale: 0.2

    - source: "IN"
      target: "OUT"
      kernel_size: 3
      stride: 1
      padding: 1
      dilation: 1
      weight_scale: 0.3

# === 작업 설정 오버라이드 ===
task:
  name: "bAbI"
  type: "reasoning"
  dataset_name: "Muennighoff/babi"
  task_id: 1 # bAbI Task 1: Single Supporting Fact
  learning_style: "bert"

  # BERT 마스킹 설정
  bert_config:
    mask_probability: 0.15 # 15% 토큰 마스킹
    random_token_prob: 0.1 # 10% 랜덤 토큰으로 대체
    unchanged_prob: 0.1 # 10% 원본 유지
    min_masks: 1 # 최소 마스크 개수
    max_masks_ratio: 0.5 # 최대 50% 마스킹

# === 학습 설정 오버라이드 ===
learning:
  epochs: 31
  learning_rate: 5e-4
  eta_min: 2e-4
  max_clk_training: 100
  optimizer: "adamw"
  weight_decay: 1e-4
  eval_every: 5
  save_every: 10
  early_stopping_patience: 100

timing_manager:
  sync_ema_alpha: 0.2 # EMA 필터링 강도
  sync_threshold_start: 0.4 # 시작 임계값
  sync_threshold_end: 0.1 # 종료 임계값
  min_processing_clk: 0 # 최소 처리 시간
  max_processing_clk: 500 # 최대 처리 시간
  min_output_length: 5 # 최소 출력 길이
  fixed_len: -1 # -1: 적응 모드, >0: 고정 길이
  fixed_delay: 3 # -1: 적응 모드, ≥0: 고정 지연

# === 데이터 로딩 오버라이드 ===
data_loading:
  batch_size: 8
  tokenizer:
    name: "t5-small"
    max_length: 128

data:
  train_samples: 100
  val_samples: 20
  test_samples: 20

# === 평가 설정 ===
evaluation:
  save_examples: 20

# === 추가 실험 설정 ===
tracking:
  use_wandb: false
  save_spike_patterns: true
  analyze_connectivity: true

# === 로깅 설정 ===
logging:
  log_metrics: ["loss", "accuracy", "f1"]
  log_frequency: 10
