# configs/phase1_babi_echo.yaml
# bAbI Echo 태스크 전용 설정

# === 기본 설정 상속 ===
defaults:
  - base_model

# === 실험 메타정보 ===
experiment:
  name: "Phase1_bAbI_Echo"
  description: "bAbI Echo Task"
  phase: 1
  expected_runtime: "30-60분"

# === 시스템 역할 (base와 동일하므로 생략 가능) ===
system_roles:
  input_node: "IN"
  output_node: "OUT"
  acc_node: "ACC"

# === 뇌 영역 구성 (완전 오버라이드) ===
brain_regions:
  IN:
    grid_size: [64, 64]
    decay_rate: 0.8
    distance_tau: 1.0
  ACC:
    grid_size: [64, 64]
    decay_rate: 0.8
    distance_tau: 1.0
  ADJ:
    grid_size: [64, 64]
    decay_rate: 0.8
    distance_tau: 1.0
  OUT:
    grid_size: [64, 64]
    decay_rate: 0.8
    distance_tau: 1.0

# === 축삭 연결 (완전 오버라이드) ===
axonal_connections:
  connections:
    # 기본 정보 처리 경로
    - source: "IN"
      target: "OUT"
      patch_size: 2
      patch_weight_scale: 1.0
      inner_weight_scale: 1.0

# === 작업 설정 오버라이드 ===
task:
  name: "bAbI"
  type: "reasoning"
  dataset_name: "Muennighoff/babi"
  task_id: 1 # bAbI Task 1: Single Supporting Fact
  learning_style: "bert"

  # BERT 마스킹 설정
  bert_config:
    mask_probability: 0.05 # 5% 토큰 마스킹
    random_token_prob: 0.1 # 10% 랜덤 토큰으로 대체
    unchanged_prob: 1.0 # 100% 원본 유지
    min_masks: 1 # 최소 마스크 개수
    max_masks_ratio: 0.5 # 최대 50% 마스킹

# === 학습 설정 오버라이드 ===
learning:
  epochs: 51
  learning_rate: 5e-4
  eta_min: 2e-4
  max_clk_training: 128
  optimizer: "adamw"
  weight_decay: 1e-4
  eval_every: 10
  save_every: 50
  early_stopping_patience: 100

  # 점진적 커리큘럼 학습
  use_curriculum_learning: true
  curriculum_schedule:
    0: 64

timing_manager:
  train_fixed_ref: "start"
  train_fixed_offset: 2
  evaluate_fixed_ref: "start"
  evaluate_fixed_offset: 2
  sync_ema_alpha: 0.1 # EMA 필터링 강도
  sync_threshold_start: 0.3 # 시작 임계값
  sync_threshold_end: 0.1 # 종료 임계값
  min_processing_clk: 0 # 최소 처리 시간
  max_processing_clk: 128 # 최대 처리 시간
  min_output_length: 5 # 최소 출력 길이

# === 데이터 로딩 오버라이드 ===
data_loading:
  batch_size: 16
  tokenizer:
    name: "t5-small"
    max_length: 128

data:
  train_samples: -1
  val_samples: -1
  test_samples: -1

# === 평가 설정 ===
evaluation:
  save_examples: 20
