# configs/phase1_squad_small.yaml
# SQuAD 독해 태스크 전용 설정

# === 기본 설정 상속 ===
defaults:
  - base_model

# === 실험 메타정보 ===
experiment:
  name: "Phase1_SQuAD_Reading"
  description: "SQuAD Reading Comprehension with Direct Attention"
  phase: 1
  expected_runtime: "30-60분"

# === 시스템 역할 (base와 동일하므로 생략 가능) ===
system_roles:
  input_node: "IN"
  output_node: "OUT"

# === 뇌 영역 구성 (완전 오버라이드) ===
brain_regions:
  IN:
    grid_size: [64, 64]
    decay_rate: 0.95
    distance_tau: 1.5
  ACC:
    grid_size: [64, 64]
    decay_rate: 0.88
    distance_tau: 2.0
  ADJ:
    grid_size: [64, 64]
    decay_rate: 0.92
    distance_tau: 2.5
  OUT:
    grid_size: [64, 64]
    decay_rate: 0.97
    distance_tau: 3.0

# === 축삭 연결 (완전 오버라이드) ===
axonal_connections:
  connections:
    # 기본 정보 처리 경로
    - source: "IN"
      target: "ADJ"
      patch_size: 2
      patch_weight_scale: 1.0
      inner_weight_scale: 1.0

    - source: "ADJ"
      target: "IN"
      patch_size: 4
      patch_weight_scale: 0.2
      inner_weight_scale: 0.2

    - source: "ADJ"
      target: "OUT"
      patch_size: 2
      patch_weight_scale: 0.9
      inner_weight_scale: 0.9

    - source: "OUT"
      target: "ADJ"
      patch_size: 4
      patch_weight_scale: 0.2
      inner_weight_scale: 0.2

    - source: "IN"
      target: "OUT"
      patch_size: 4
      patch_weight_scale: 0.3
      inner_weight_scale: 0.3

# === 작업 설정 오버라이드 ===
task:
  name: "SQuAD"
  type: "reading_comprehension"
  dataset_name: "rajpurkar/squad"
  task_id: 1

# === 학습 설정 오버라이드 ===
learning:
  epochs: 100
  learning_rate: 5e-5
  max_clk_training: 550
  optimizer: "adamw"
  weight_decay: 0.01
  eval_every: 5
  save_every: 10
  early_stopping_patience: 5

  gradual_unfreezing:
    enabled: true
    initial_frozen_patterns: # 시작할 때 동결할 파라미터들
      - "input_interface.token_embedding"
      - "output_interface.token_embedding"
      - "output_interface.final_projection"
    unfreeze_schedule: # 에포크별 해제 스케줄
      30: # 에포크 30에 T5 임베딩 해제 (기존과 동일)
        - "input_interface.token_embedding"
        - "output_interface.token_embedding"
        - "output_interface.final_projection"

timing_manager:
  train_fixed_ref: "start"
  train_fixed_offset: 2
  evaluate_fixed_ref: "start"
  evaluate_fixed_offset: 2
  sync_ema_alpha: 0.1 # EMA 필터링 강도
  sync_threshold_start: 0.6 # 시작 임계값
  sync_threshold_end: 0.2 # 종료 임계값
  min_processing_clk: 50 # 최소 처리 시간
  max_processing_clk: 500 # 최대 처리 시간
  min_output_length: 5 # 최소 출력 길이

# === 데이터 로딩 오버라이드 ===
data_loading:
  batch_size: 8
  tokenizer:
    name: "t5-small"
    max_length: 512

data:
  train_samples: 1000
  val_samples: 100
  test_samples: 100

# === 평가 설정 ===
evaluation:
  save_examples: 5
